// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Button(props) {
  return JsxRuntime.jsx("button", {
              children: props.children,
              className: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded",
              onClick: props.onClick
            });
}

var make = Button;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
