// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "../shared/ui/Button.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Reducer(props) {
  var match = React.useReducer((function (state, action) {
          switch (action) {
            case "Toggle" :
                if (state === "ActiveValue") {
                  return "InactiveValue";
                } else {
                  return "ActiveValue";
                }
            case "Active" :
                return "ActiveValue";
            case "Inactive" :
                return "InactiveValue";
            
          }
        }), "InactiveValue");
  var dispatch = match[1];
  var tmp;
  tmp = match[0] === "ActiveValue" ? "Active" : "Inactive";
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Reducer",
                      className: "text-lg"
                    }),
                JsxRuntime.jsx("div", {
                      children: tmp,
                      className: "text-3xl text-center m-5 text-gray-700"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(Button.make, {
                              children: "Toggle",
                              onClick: (function (param) {
                                  dispatch("Toggle");
                                })
                            }),
                        JsxRuntime.jsx(Button.make, {
                              children: "Active",
                              onClick: (function (param) {
                                  dispatch("Active");
                                })
                            }),
                        JsxRuntime.jsx(Button.make, {
                              children: "Inactive",
                              onClick: (function (param) {
                                  dispatch("Inactive");
                                })
                            })
                      ],
                      className: "flex gap-5 justify-center w-full"
                    })
              ],
              className: "text-center m-5 p-5 rounded-sm bg-lime-100"
            });
}

var make = Reducer;

export {
  make ,
}
/* react Not a pure module */
