// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "../shared/ui/Button.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Reducer(props) {
  var match = React.useReducer((function (state, action) {
          if (state === "Active") {
            return "Inactive";
          } else {
            return "Active";
          }
        }), "Inactive");
  var dispatch = match[1];
  var tmp;
  tmp = match[0] === "Active" ? "Active" : "Inactive";
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Reducer",
                      className: "text-lg"
                    }),
                JsxRuntime.jsx("div", {
                      children: tmp,
                      className: "text-3xl text-center m-5 text-gray-700"
                    }),
                JsxRuntime.jsx(Button.make, {
                      children: "Click Me!",
                      onClick: (function (param) {
                          dispatch("Toggle");
                        })
                    })
              ],
              className: "text-center m-5 p-5 rounded-sm bg-lime-100"
            });
}

var make = Reducer;

export {
  make ,
}
/* react Not a pure module */
