// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "./shared/ui/Button.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = React.useState(function () {
        return false;
      });
  var setActive = match[1];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: match[0] ? "Active" : "Not Active",
                      className: "text-3xl text-center m-5 text-gray-700"
                    }),
                JsxRuntime.jsx(Button.make, {
                      children: "Click me",
                      onClick: (function (param) {
                          setActive(function (active) {
                                return !active;
                              });
                        })
                    })
              ],
              className: "text-center m-5"
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
