// Generated by ReScript, PLEASE EDIT WITH CARE

import * as State from "./features/State.mjs";
import * as Reducer from "./features/Reducer.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(State.make, {}),
                JsxRuntime.jsx(Reducer.make, {})
              ],
              className: "text-center m-5 flex-row gap-5"
            });
}

var make = App;

export {
  make ,
}
/* State Not a pure module */
