// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx("p", {
    children: "Hello!",
  });
}

var make = App;

export { make };
/* react/jsx-runtime Not a pure module */
